version: '2'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    image: reki-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
