# Custom build of a Herokulike node environment with a more recent node version
FROM heroku/heroku:18

COPY .nvmrc ./

# Install the specified Heroku node version
RUN curl -s "https://s3pository.heroku.com/node/v$(cat .nvmrc)/node-v$(cat .nvmrc)-linux-x64.tar.gz" | tar --strip-components=1 -xz -C /usr/local \
&& ln -s /usr/local/bin/node /usr/local/bin/nodejs
