# Custom build of a Herokulike node environment with a more recent node version
FROM heroku/heroku:16

# Refer to the list of available node versions on Heroku
ENV NODE_VERSION 8.11.2

# Install the specified Heroku node version
RUN curl -s https://s3pository.heroku.com/node/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz | tar --strip-components=1 -xz -C /usr/local \
&& ln -s /usr/local/bin/node /usr/local/bin/nodejs
