version: 2
jobs:
  install:
    docker:
      - image: circleci/node:10.16.3-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-node10.16.3
      - run:
          name: npm install
          command: |
            if [ ! -d node_modules ]; then
              npm ci --production=false
            fi
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-node10.16.3
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:10.16.3-browsers
        environment:
          TEST_DATABASE_URL: postgres://reki@localhost/reki
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: reki
          POSTGRES_DB: reki
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-node10.16.3
      - run:
          name: Linter
          command: npm run linter
      - run:
          name: Functional tests
          command: npm run test-functional
      - run:
          name: Integration tests
          command: npm run test-integration
workflows:
  version: 2
  install_and_test:
    jobs:
      - install
      - test:
          requires:
            - install
