version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.16.3-browsers
        environment:
          TEST_DATABASE_URL: postgres://reki@localhost/reki
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: reki
          POSTGRES_DB: reki
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-node10.16.3
      - run:
          name: npm install
          command: |
            if [ ! -d node_modules ]; then
              npm ci --production=false
            else
              echo "Using cached dependencies"
            fi
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-node10.16.3
          paths:
            - node_modules
      - run:
          name: Linter
          command: npm run linter -- --format junit -o ~/reporters/tslint.xml
      - run:
          name: Functional tests
          command: npm run test-functional -- --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ~/reports/functional-tests.xml
      - run:
          name: Integration tests
          command: npm run test-integration -- --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ~/reports/integration-tests.xml
      - store_test_results:
          path: ~/reports
workflows:
  version: 2
  install_and_test:
    jobs:
      - test
