version: 2
jobs:
  install:
    docker:
      - image: circleci/node:10.16.3-browsers
    steps:
      - checkout
      - run:
          name: Download Selenium
          command: wget --no-verbose -O "selenium-server-standalone.jar" "http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar"
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-node10.16.3
          paths:
            - node_modules
      - save_cache:
          key: selenium-cache-2.53.1
          paths:
            - selenium-server-standalone.jar
  test:
    docker:
      - image: circleci/node:10.16.3-browsers
        environment:
          TEST_DATABASE_URL: postgres://reki@localhost/reki
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: reki
          POSTGRES_DB: reki
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-node10.16.3
      - restore_cache:
          key: selenium-cache-2.53.1
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone.jar
          background: true
      - run: npm test
workflows:
  version: 2
  install_and_test:
    jobs:
      - install
      - test:
          requires:
            - install
