version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.16.3-browsers
        environment:
          TEST_DATABASE_URL: postgres://reki@localhost/reki
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: reki
          POSTGRES_DB: reki
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum ".nvmrc" }}
      - run:
          name: npm install
          command: |
            if [ ! -d node_modules ]; then
              npm ci --production=false
            else
              echo "Using cached dependencies"
            fi
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum ".nvmrc" }}
          paths:
            - node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: Functional tests
          command: npm run test-functional
      - run:
          name: Integration tests
          command: npm run test-integration
      - run:
          name: End-to-end tests
          command: npm run test-e2e
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ./logs
workflows:
  version: 2
  install_and_test:
    jobs:
      - test
